WCCILdata    (0), 2019.04.12 10:46:10.916, SYS,  INFO,        1, Manager Start, PROJ, Conveyor, V 3.15 - 3.15   platform Windows AMD64 linked at Jan 31 2019 19:30:43 (3914f9beaa1)
WCCILdata    (0), 2019.04.12 10:46:10.922, SYS,  INFO,        0, , (Re)Opening databases in single user mode without transaction logging.
WCCILdata    (0), 2019.04.12 10:46:11.499, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2019.04.12 10:46:11.501, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2019.04.12 10:46:11.501, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2019.04.12 10:46:11.502, SYS,  INFO,        0, , Initializing last value cache
WCCILdata    (0), 2019.04.12 10:46:11.503, SYS,  INFO,        0, , Loading internal datapoints
WCCILdata    (0), 2019.04.12 10:46:11.504, SYS,  INFO,        0, , Initializing ID history
WCCILdata    (0), 2019.04.12 10:46:11.504, SYS,  INFO,        0, , Initializing Alert history
WCCILdata    (0), 2019.04.12 10:46:11.504, SYS,  INFO,        0, , Initializing Alert Class cache
WCCILdata    (0), 2019.04.12 10:46:11.506, SYS,  INFO,        6, Initialization by Data Manager finished
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.arNr:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.state:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arType:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arName:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.createArchive:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.forwardToRDB:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errNum:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.506, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errDp:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errBit:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errRead:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheGet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.aliveInterval:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.saveCycle:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validFrom:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validUntil:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.time:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.weekDay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.507, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.monthDay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.month:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncTime:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncWeekDay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncDay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncMonth:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.interval:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.delay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validFrom:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validUntil:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.time:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.weekDay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.monthDay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.month:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncTime:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncWeekDay:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.508, SYS,  SEVERE,    118, Last error already repeated 50 times. Until another output occurs, this one will be blocked.
WCCILdata    (0), 2019.04.12 10:46:11.510, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileCompression.autoStartAfterSwitchSet:_original.._value
WCCILdata    (0), 2019.04.12 10:46:11.510, SYS,  INFO,      119, Last error repeated 213 times.
WCCILdata    (0), 2019.04.12 10:46:11.510, SYS,  INFO,        0, , Initializing Value Archives
WCCILdata    (0), 2019.04.12 10:46:11.510, SYS,  INFO,        0, , ValueArchive will be used...
WCCILdata    (0), 2019.04.12 10:46:11.829, SYS,  INFO,        4, Connected to (SYS: 1 Event -num 0 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:11.833, SYS,  INFO,        0, , Manager (SYS: 1 Event -num 0 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:11.976, SYS,  INFO,        4, Connected to (SYS: 1 Driver -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:11.979, SYS,  INFO,        0, , Manager (SYS: 1 Driver -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:12.132, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:12.134, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:12.494, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:12.639, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:12.644, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:12.717, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:12.861, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:12.866, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:13.258, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:13.396, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:13.400, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:13.438, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:13.578, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:13.582, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:13.612, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:13.754, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:13.759, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:13.809, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:14.079, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:14.083, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:17.663, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:17.808, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:17.812, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:17.843, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:17.984, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:17.987, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:18.109, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:18.364, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-J5M05O0 (::1)
WCCILdata    (0), 2019.04.12 10:46:18.368, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2019.04.12 10:46:18.396, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2019.04.12 10:46:20.431, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Driver -num 1 CONN: 1), Connection closed
WCCILdata    (0), 2019.04.12 10:46:22.538, SYS,  INFO,      181, Closing connection to (SYS: 1 Event -num 0 CONN: 1)
WCCILdata    (0), 2019.04.12 10:46:22.538, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Event -num 0 CONN: 1), Connection closed
WCCILdata    (0), 2019.04.12 10:46:22.585, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2019.04.12 10:46:22.820, SYS,  INFO,        2, Manager Stop
